Added runtime environment alteration tests coverage

diff --git a/unittest b/unittest
--- a/unittest
+++ b/unittest
@@ -18,7 +18,7 @@ shopt -s extdebug
 errors=0
 disabled=0
 
-rm -f unittest.log
+rm -f unittest.log unittest.env.log
 
 err_trap() {
 	: $((errors+=1))
@@ -56,7 +56,7 @@ print_exit_status() {
 }
 
 echo_for_print_status() {
-    local m="$1"
+    local m=$1
     if tty >/dev/null 2>&1 && [[ -n "${PRINT_STATUS_COLOR:-}" ]]
     then
         m="$(tput setaf $PRINT_STATUS_COLOR)$m$(tput sgr0)"
@@ -71,9 +71,9 @@ exec_and_print_status() {
     # all other parameter: the command to execute
     # returns the exit status code of the command
     [[ $# -lt 2 ]] && return 1
-    local m="$1" ; shift
+    local m=$1 ; shift
     PRINT_STATUS_COLOR="${PRINT_STATUS_COLOR-}" \
-		      echo_for_print_status "$m"
+		echo_for_print_status "$m"
     "$@"
     print_exit_status $?
 }
@@ -86,17 +86,45 @@ failure() {
 	[[ $? -ne 0 ]]
 }
 
+shell_env() {
+	# Greps are:
+	# * variables automatically altered by bash itself.
+	# * local environment variables, used by the environment checking routines.
+	# * argsparse private variables, subjects to modifications/deletion.
+	# * argsparse public variables.
+	# * argsparse results, which are expected to change.
+	set | \
+		grep -vE '^(FIRST|SECOND|SHELLOPTS|FUNCNAME|_|LINENO|BASH_(ARG[CV]|LINENO|SOURCE|REMATCH)|PIPESTATUS)=' | \
+		grep -vE '^before=' | \
+		grep -vE '^__argsparse_(options_descriptions|short_options|tmp_identifiers)=' | \
+		grep -vE '^argsparse_usage_description=' | \
+		grep -vE '^(program_(params|options))|cumulated_values_[0-9a-zA-Z_]+='
+	shopt
+	set -o | grep -v xtrace
+}
+
+check_env() {
+	{
+		printf "For test: %s\n" "$message"
+		diff -u <(echo "$before") <(shell_env)
+	} >> unittest.env.log
+}
+
 parse_option_wrapper() {
 	local message=$1
 	local TEST=${TEST:-default_test}
 	shift
+	local before=$(shell_env)
 	echo_for_print_status "Checking $message"
 	(
 		printf "Test is: %s\n" "$message"
 		printf "Validation is: %s\n" "$TEST"
 		set -x
-		argsparse_parse_options "$@"
-		${INNERTEST:-exit $?}
+		(
+			trap check_env EXIT
+			argsparse_parse_options "$@"
+			${INNERTEST:-exit $?}
+		)
 	) >>unittest.log 2>&1
 	$TEST
 	print_exit_status || exit
@@ -401,16 +429,32 @@ rm -Rf "$dir"
 	TEST=failure parse_option_wrapper "custom type (2)" --option asdf
 )
 
-printf "Report:\n"
+printf "Tests report:\n"
 if [[ $disabled -ne 0 ]]
 then
-	printf "%d test(s) disabled.\n" "$disabled"
+	printf "* %d test(s) disabled.\n" "$disabled"
 fi
 
 if [[ $errors -ne 0 ]]
 then
-	printf "%d error(s) encountered. (See above)\n" "$errors"
-	printf "Environment was:\n"
+	printf "* %* d error(s) encountered. (See above)\n" "$errors"
+	exit_code=1
+else
+	printf "All tests passed.\n"
+	exit_code=0
+fi
+
+printf "Environment alteration detected:\n"
+if grep -v -B 1 '^For test:' unittest.env.log
+then
+	: exit_code $((exit_code))
+else
+	printf "None.\n"
+fi
+
+if [[ $exit_code -ne 0 ]]
+then
+	printf "Runtime environment was:\n"
 	set -x
 	{
 		command -v bash
@@ -418,8 +462,6 @@ then
 		shopt
 		set -o
 	} 2>&1
-	exit 1
-else
-	printf "All tests passed.\n"
-	exit 0
 fi
+
+exit "$exit_code"
